# Utilizamos una imagen base oficial de Node.js
FROM node:18-alpine

# Establecemos el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiamos los archivos de configuración y las dependencias del proyecto
COPY package*.json ./

# Instalamos las dependencias de producción y desarrollo
RUN npm install

# Copiamos el resto del código fuente de la aplicación
COPY . .

# Exponemos el puerto utilizado por Nuxt (por defecto, el 3000)
EXPOSE 3000

# Comando por defecto para iniciar la aplicación en producción
CMD ["npm", "run", "dev"]]